-- Defines stable cross-resource technical error codes.
---@class CnrErrorCodes
local ErrorCodes = {
    VALIDATION_ERROR = 'VALIDATION_ERROR',
    AUTHENTICATION_REQUIRED = 'AUTHENTICATION_REQUIRED',
    IDENTIFIER_REQUIRED = 'IDENTIFIER_REQUIRED',
    IDENTIFIER_CONFLICT = 'IDENTIFIER_CONFLICT',
    REGISTRATION_DISABLED = 'REGISTRATION_DISABLED',
    ACCOUNT_BANNED = 'ACCOUNT_BANNED',
    ACCOUNT_RESTRICTED = 'ACCOUNT_RESTRICTED',
    WHITELIST_REQUIRED = 'WHITELIST_REQUIRED',
    SESSION_ALREADY_ACTIVE = 'SESSION_ALREADY_ACTIVE',
    CHARACTER_REQUIRED = 'CHARACTER_REQUIRED',
    PERMISSION_DENIED = 'PERMISSION_DENIED',
    RATE_LIMITED = 'RATE_LIMITED',
    NOT_FOUND = 'NOT_FOUND',
    CONFLICT = 'CONFLICT',
    PRECONDITION_FAILED = 'PRECONDITION_FAILED',
    INSUFFICIENT_FUNDS = 'INSUFFICIENT_FUNDS',
    INSUFFICIENT_CAPACITY = 'INSUFFICIENT_CAPACITY',
    DEPENDENCY_UNAVAILABLE = 'DEPENDENCY_UNAVAILABLE',
    MAINTENANCE_MODE = 'MAINTENANCE_MODE',
    INTERNAL_ERROR = 'INTERNAL_ERROR',
}

return ErrorCodes
